apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-reproduce-v133
  region: us-east-1
  version: "1.33"

nodeGroups:
  - name: kernel-6-1-m6i-8xlarge
    amiFamily: Bottlerocket
    # bottlerocket-aws-k8s-1.32-x86_64-v1.44.0-244cd3a5 (Kernel 6.1.144)
    ami: ami-0026d8294bcd292ca
    desiredCapacity: 1
    instanceType: m6i.8xlarge
    volumeSize: 100
    volumeType: gp3
    privateNetworking: true
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    maxPodsPerNode: 500 # Tested, m6i.8xlarge should be able to hold 500 pods per node

  - name: kernel-6-12-m6i-8xlarge
    amiFamily: Bottlerocket
    # bottlerocket-aws-k8s-1.33-x86_64-v1.51.0-47438798 (Kernel 6.12.55)
    ami: ami-04aa24218c21b7691
    desiredCapacity: 1
    instanceType: m6i.8xlarge
    volumeSize: 100
    volumeType: gp3
    privateNetworking: true
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    maxPodsPerNode: 500 # Tested, m6i.8xlarge should be able to hold 500 pods per node

addons:
  - name: kube-proxy
    configurationValues: '{"mode": "nftables"}'
    version: 'v1.33.5-eksbuild.2'
  - name: vpc-cni
    configurationValues: '{"env": {"ENABLE_PREFIX_DELEGATION": "true","WARM_PREFIX_TARGET": "50"}}' # to ensure we could scaling fast.
    version: 'v1.20.5-eksbuild.1'
  - name: coredns
    configurationValues: '{"resources":{"requests":{"cpu":"1000m","memory":"1000Mi"},"limits":{"memory":"1200Mi"}},"autoScaling":{"enabled":true}}' # to ensure coredns would not crash.
    version: 'v1.12.4-eksbuild.1'
  - name: metrics-server
    version: 'v0.8.0-eksbuild.5'
